  !rate enum
  integer, parameter :: betaplus = 1
  integer, parameter :: ecapture = 2
  integer, parameter :: elossnue = 3
  integer, parameter :: betaminus = 4
  integer, parameter :: poscapture = 5
  integer, parameter :: elossanue = 6

  !eos enum
  integer, parameter :: total_eos_variables = 15
  integer, parameter :: rhoindex =1
  integer, parameter :: tempindex = 2
  integer, parameter :: yeindex = 3
  integer, parameter :: energyindex = 4
  integer, parameter :: xaindex = 5
  integer, parameter :: xhindex = 6
  integer, parameter :: xnindex = 7
  integer, parameter :: xpindex = 8
  integer, parameter :: abarindex = 9
  integer, parameter :: zbarindex = 10
  integer, parameter :: mueindex = 11
  integer, parameter :: munindex = 12
  integer, parameter :: mupindex = 13
  integer, parameter :: muhatindex = 14
  integer, parameter :: entropyindex = 15
